{{- if and .Values.rbac.create .Values.rbac.namespaced }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "spring-boot.fullname" . }}-rolebinding
  namespace: {{ template "spring-boot.namespace" . }}
  labels:
    {{- include "spring-boot.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
subjects:
- kind: ServiceAccount
  name: {{ template "spring-boot.serviceAccountName" . }}
  namespace: {{ template "spring-boot.namespace" . }}
roleRef:
  kind: Role
  name: {{ .Values.rbac.existingRole }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
